apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/todo_db"
  SPRING_DATASOURCE_USERNAME: "todo_user"
  SPRING_DATASOURCE_PASSWORD: "todo_pass"

  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
